package com.cphillipsdorsett.teamsweeper.game;

import org.springframework.stereotype.Repository;

import javax.persistence.EntityManager;
import javax.transaction.Transactional;
import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

/**
 * Class to Combine all of the methods of a spring autogenerated Repository,
 * e.g., "findById", but creates additional methods to run raw sql using an
 * EntityManager.
 */
@Repository
public class GameDao implements GameRepository {

    EntityManager em;
    GameRepository gameRepository;

    public GameDao(EntityManager entityManager, GameRepository gameRepository) {
        em = entityManager;
        this.gameRepository = gameRepository;
    }

    @Transactional
    public Game create(Game game) {
        int num = em
            .createNativeQuery("" +
                "INSERT INTO game (difficulty, mines, non_mines, board, total_cells) " +
                "VALUES (?, ?, ?, ?, ?);"
            )
            .setParameter(1, game.difficulty)
            .setParameter(2, game.mines)
            .setParameter(3, game.nonMines)
            .setParameter(4, game.board)
            .setParameter(5, game.totalCells)
            .executeUpdate();
        return (Game) em
            .createNativeQuery("" +
                "SELECT g.* " +
                "FROM game g " +
                "WHERE g.id = (SELECT LAST_INSERT_ID())",
                Game.class
            )
            .getSingleResult();
    }

    @Transactional
    public Game findBySessionId(String session_id) {
        List<Game> results = (List<Game>) em
            .createNativeQuery("" +
                "SELECT g.* " +
                "FROM game g " +
                "INNER JOIN session_game sg ON g.id = sg.game_id " +
                "INNER JOIN SPRING_SESSION ss ON sg.session_id = ss.SESSION_ID " +
                "WHERE ss.SESSION_ID = ?",
                Game.class
            )
            .setParameter(1, session_id)
            .getResultList();
        return results.isEmpty() ? null : results.get(0);
    }

    @Override
    public <S extends Game> S save(S entity) {
        return gameRepository.save(entity);
    }

    @Override
    public <S extends Game> Iterable<S> saveAll(Iterable<S> entities) {
        return gameRepository.saveAll(entities);
    }

    @Override
    public Optional<Game> findById(Integer integer) {
        return gameRepository.findById(integer);
    }

    @Override
    public boolean existsById(Integer integer) {
        return gameRepository.existsById(integer);
    }

    @Override
    public Iterable<Game> findAll() {
        return gameRepository.findAll();
    }

    @Override
    public Iterable<Game> findAllById(Iterable<Integer> integers) {
        return gameRepository.findAllById(integers);
    }

    @Override
    public long count() {
        return gameRepository.count();
    }

    @Override
    public void deleteById(Integer integer) {
        gameRepository.deleteById(integer);
    }

    @Override
    public void delete(Game entity) {
        gameRepository.delete(entity);
    }

    @Override
    public void deleteAll(Iterable<? extends Game> entities) {
        gameRepository.deleteAll(entities);
    }

    @Override
    public void deleteAll() {
        gameRepository.deleteAll();
    }
}
