package com.cphillipsdorsett.teamsweeper.game.dao;

import org.springframework.stereotype.Repository;

import javax.persistence.EntityManager;
import javax.transaction.Transactional;
import java.math.BigInteger;
import java.util.Optional;

/**
 * Class to Combine all the methods of a spring autogenerated Repository, e.g.,
 * "findById", but creates additional methods to run raw sql using an
 * EntityManager.
 */
@Repository
public class GameDao implements GameRepository {
    EntityManager em;
    GameRepository gameRepository;

    public GameDao(EntityManager entityManager, GameRepository gameRepository) {
        em = entityManager;
        this.gameRepository = gameRepository;
    }

    @Transactional
    public Game create(Game game) {
        em
            .createNativeQuery("" +
                "INSERT INTO game (difficulty, status, board) " +
                "VALUES (:difficulty, :status, :board)"
            )
            .setParameter("difficulty", game.getDifficulty().name())
            .setParameter("status", game.getStatus().name())
            .setParameter("board", game.getBoard())
            .executeUpdate();
        return (Game) em
            .createNativeQuery(
                "" +
                    "SELECT g.* " +
                    "FROM game g " +
                    "WHERE g.id = (SELECT LAST_INSERT_ID())",
                Game.class
            )
            .getSingleResult();
    }

    @Transactional
    public Game findCurrent(String sessionId, int gameId) {
        return (Game) em
            .createNativeQuery(
                "" +
                    "SELECT g.* " +
                    "FROM game g " +
                    "INNER JOIN session_game sg ON g.id = sg.game_id " +
                    "WHERE sg.session_id = :sessionId " +
                    "    AND g.id = :gameId",
                Game.class
            )
            .setParameter("sessionId", sessionId)
            .setParameter("gameId", gameId)
            .getSingleResult();
    }

    @Transactional
    public void update(Game game) {
        em
            .createNativeQuery("" +
                "UPDATE game g " +
                "SET" +
                "    g.board = :board," +
                "    g.status = :status," +
                "    g.started_at = :startedAt," +
                "    g.ended_at = :endedAt " +
                "WHERE g.id = :gameId"
            )
            .setParameter("board", game.getBoard())
            .setParameter("status", game.getStatus().toString())
            .setParameter("startedAt", game.getStartedAt())
            .setParameter("endedAt", game.getEndedAt())
            .setParameter("gameId", game.getId())
            .executeUpdate();
    }

    /**
     * Delete games that don't a http session associated with them
     */
    @Transactional
    public int deleteGamesWithoutSession() {
        em
            .createNativeQuery("" +
                "DELETE g FROM game g " +
                "LEFT JOIN session_game sg ON sg.game_id = g.id " +
                "WHERE sg.session_id IS NULL"
            )
            .executeUpdate();
        BigInteger deletedCount = (BigInteger) em
            .createNativeQuery("" +
                "SELECT ROW_COUNT()"
            )
            .getSingleResult();
        return deletedCount.intValue();
    }

    @Override
    public <S extends Game> S save(S entity) {
        return gameRepository.save(entity);
    }

    @Override
    public <S extends Game> Iterable<S> saveAll(Iterable<S> entities) {
        return gameRepository.saveAll(entities);
    }

    @Override
    public Optional<Game> findById(Integer integer) {
        return gameRepository.findById(integer);
    }

    @Override
    public boolean existsById(Integer integer) {
        return gameRepository.existsById(integer);
    }

    @Override
    public Iterable<Game> findAll() {
        return gameRepository.findAll();
    }

    @Override
    public Iterable<Game> findAllById(Iterable<Integer> integers) {
        return gameRepository.findAllById(integers);
    }

    @Override
    public long count() {
        return gameRepository.count();
    }

    @Override
    public void deleteById(Integer integer) {
        gameRepository.deleteById(integer);
    }

    @Override
    public void delete(Game entity) {
        gameRepository.delete(entity);
    }

    @Override
    public void deleteAll(Iterable<? extends Game> entities) {
        gameRepository.deleteAll(entities);
    }

    @Override
    public void deleteAll() {
        gameRepository.deleteAll();
    }
}
